# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - avoid_returning_null
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - package_api_docs
